# Generated by Django 5.1.6 on 2025-03-04 08:36

import lmsApi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[lmsApi.models.validate_amount]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='tenure',
            field=models.IntegerField(validators=[lmsApi.models.validate_tenure]),
        ),
    ]
